/*
 * generated by Xtext
 */
package at.ac.tuwien.big.ui.contentassist

import at.ac.tuwien.big.ui.contentassist.AbstractQuestionnaireProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class QuestionnaireProposalProvider extends AbstractQuestionnaireProposalProvider {
}
