/*
 * generated by Xtext
 */
package at.ac.tuwien.big.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class QuestionnaireUiModule extends at.ac.tuwien.big.ui.AbstractQuestionnaireUiModule {
	public QuestionnaireUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
